/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.visao;

import com.mycompany.controle.Controle_Sistema;
import com.mycompany.modelo.Computador;
import com.mycompany.modelo.VideoGame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sthefany.1921
 */
public class Listagem extends javax.swing.JFrame {

    /**
     * Creates new form Listagem
     */
    public Listagem() {
        initComponents();
        
        listarTodos();
    }
    
    public static void listarTodos(){
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("Informações");
        defaultTableModel.addColumn("Categoria");
        tableListagem.setModel(defaultTableModel);
        defaultTableModel.setRowCount(0);
        
        for(int i=0; i < Controle_Sistema.produtos.size(); i++){
            Object[] linha = new Object[defaultTableModel.getColumnCount()];
            defaultTableModel.addRow(linha);
            
            if(Controle_Sistema.produtos.get(i) instanceof Computador){
                tableListagem.setValueAt(((Computador) Controle_Sistema.produtos.get(i)).getNome(), i, 0);
                tableListagem.setValueAt("Computador", i, 1);
            }else if(Controle_Sistema.produtos.get(i) instanceof VideoGame){
                tableListagem.setValueAt(((VideoGame) Controle_Sistema.produtos.get(i)).getNome(), i, 0);
                tableListagem.setValueAt("Vídeo Game", i, 1);
            }
        }
    }
    
    public static void listarComputador(){
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        
        defaultTableModel.addColumn("Nome");
        defaultTableModel.addColumn("Preço");
        defaultTableModel.addColumn("Memória Ram");
        defaultTableModel.addColumn("Processador");
        
        tableListagem.setModel(defaultTableModel);
        
        defaultTableModel.setRowCount(0);
        
        int linhaCont = 0;
        
        for(int i=0; i < Controle_Sistema.produtos.size(); i++){
            if(Controle_Sistema.produtos.get(i) instanceof Computador){
                Object[] linha = new Object[defaultTableModel.getColumnCount()];
                defaultTableModel.addRow(linha);
                tableListagem.setValueAt(((Computador) Controle_Sistema.produtos.get(i)).getNome(), linhaCont, 0);
                tableListagem.setValueAt(((Computador) Controle_Sistema.produtos.get(i)).getPreco(), linhaCont, 1);
                tableListagem.setValueAt(((Computador) Controle_Sistema.produtos.get(i)).getMemoriaRam(), linhaCont, 2);
                tableListagem.setValueAt(((Computador) Controle_Sistema.produtos.get(i)).getProcessador(), linhaCont, 3);
                
                linhaCont++;
            }
        }
    }
    
    public static void listarVideoGame(){
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        
        defaultTableModel.addColumn("Nome");
        defaultTableModel.addColumn("Preço");
        defaultTableModel.addColumn("Plataforma");
        
        tableListagem.setModel(defaultTableModel);
        
        defaultTableModel.setRowCount(0);
        
        int linhaCont = 0;
        
        
        for(int i = 0; i< Controle_Sistema.produtos.size(); i++){
            if(Controle_Sistema.produtos.get(i) instanceof VideoGame){
                Object[] linha = new Object[defaultTableModel.getColumnCount()];
                defaultTableModel.addRow(linha);
                tableListagem.setValueAt(((VideoGame) Controle_Sistema.produtos.get(i)).getNome(), linhaCont, 0);
                tableListagem.setValueAt(((VideoGame) Controle_Sistema.produtos.get(i)).getPreco(), linhaCont, 1);
                tableListagem.setValueAt(((VideoGame) Controle_Sistema.produtos.get(i)).getPlataforma(), linhaCont, 2);
                
                linhaCont++;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbCategorias = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListagem = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Computador", "Vídeo Game" }));
        cbCategorias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCategoriasItemStateChanged(evt);
            }
        });
        cbCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriasActionPerformed(evt);
            }
        });

        tableListagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Informações", "Categoria"
            }
        ));
        jScrollPane1.setViewportView(tableListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCategoriasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCategoriasItemStateChanged
        if(cbCategorias.getSelectedIndex() == 0){
            listarTodos();
        }
    }//GEN-LAST:event_cbCategoriasItemStateChanged

    private void cbCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCategoriasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCategorias;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable tableListagem;
    // End of variables declaration//GEN-END:variables
}
